name: Vercel-cron
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel deploy webhook
        run: |
          curl -X POST ${{ secrets.VERCEL_HOOKS }}
